version: 0.2

phases:
  install:
    commands:
      - yum install epel-release -y
      - yum install nodejs -y
      - yum install gcc -y
      - yum install make -y
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ./node_modules/.bin/gulp condensation:build
      - ./node_modules/.bin/gulp condensation:deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/0